### PR TITLE
Correct some URLs

### PR DESCRIPTION
**Pull request by peternewman**

### CODE REVIEW

**Comment by jswalden** [comment]
I have this change as part of https://github.com/bitfocus/companion-module-ptzoptics-visca/pull/30 as well. 🙂 Obviously it doesn't matter which one of us wins, tho!

**Comment by peternewman** [comment]
Oops, I didn't even think to check. Well I guess we can see who gets in first @jswalden ! :runner:

**Comment by jswalden** [comment]
Seems hardly reasonable to me to expect you to find it in one of several commits in a vaguely-named issue.  :-)

**Comment by peternewman** [comment]
Well @Julusian managed to merge them at the same minute somehow @jswalden so I think you win as your commits were in earlier chronologically! 😆

**Pull request merged**
